### ISSUE TITLE
Can it be run with CPU?

### ISSUE THREAD

**Issue by jonhassall** [fofr/cog-face-to-sticker#12]
Can it be run with CPU (no GPU)?

**Comment by fofr** [comment]
Probably not. An M3 Mac maybe

**Comment by jonhassall** [comment]
Thanks.

**Comment by tuxfamily** [comment]
> Probably not. An M3 Mac maybe

Hello.

I'm trying to run it on a Mac Studio M1 Max but obviously it fails.

Of course, Docker reports this notice:
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
Missing device driver, re-trying without GPU
```

And when launching main.py:

```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

So, dumb question: how we can launch it on CPU?

Sorry, I'm totally new in this domain and did not found any real way to fix this (for a mac), googling this issue.

Thanks for your help.
