### ISSUE TITLE
run it on comfyui, the output image is noise image

### ISSUE THREAD

**Issue by oftenliu** [fofr/cog-face-to-sticker#4]
![image](https://github.com/fofr/cog-face-to-sticker/assets/20364898/3b8dd5f8-7af6-4b3b-9927-0b88b8c5ddb9)

@fofr

**Comment by Ilyaprok** [comment]
same problem

**Comment by Ilyaprok** [comment]
need to update the ComfyUI

**Comment by fofr** [comment]
Yes, the InstantID modules depend on a newer version of ComfyUI, there were some changes made to that they'd work.
